Task/test amazon notebook
Giskard-AI/examples pull request #17
Opened 2023-05-02 13:49 UTC by AbSsEnT

Prepared a notebook "amazon_review_classification_giskard_example.ipynb" with examples of use of a standard giskard functionality: model and dataset wrapping, model scan.
https://linear.app/giskard/issue/GSK-1006/amazon-review-notebook

2023-05-02 14:20 UTC, rabah-khalek requested changes

2023-05-02 14:20 UTC, rabah-khalek commented on amazon_review_classification_reference.ipynb
Could you please remove [amazon_review_classification_reference.ipynb](https://github.com/Giskard-AI/giskard-examples/pull/17/files#diff-9e871edec5bfeda3564c19fac7fdb9e4832d0628e60b892a587caa26e6be5de6) and instead put a link towards the original notebook inside [amazon_review_classification_giskard_example.ipynb](https://github.com/Giskard-AI/giskard-examples/pull/17/files#diff-8d61555e07a9d37f09f0299d039f4894515bce2512086b3d64637c58597ccaef)?

2023-05-02 14:20 UTC, rabah-khalek commented on amazon_review_classification_giskard_example.ipynb
Could you just name [amazon_review_classification_giskard_example.ipynb](https://github.com/Giskard-AI/giskard-examples/pull/17/files#diff-8d61555e07a9d37f09f0299d039f4894515bce2512086b3d64637c58597ccaef), `amazon_review_classification_sklearn.ipynb` instead?

2023-05-02 14:20 UTC, rabah-khalek commented on amazon_review_classification_giskard_example.ipynb
Could you add `!pip install nltk giskard` in a separate cell at the beginning?

2023-05-02 14:20 UTC, rabah-khalek commented on amazon_review_classification_giskard_example.ipynb
Could you also remove the last line from:
```py
reviews_df = download_data()
reviews_df = preprocess_data(reviews_df)
reviews_df
```

2023-05-02 14:20 UTC, rabah-khalek commented on amazon_review_classification_giskard_example.ipynb
Add two additional parts to the notebooks:
1. https://giskard.readthedocs.io/en/latest/getting-started/scan/index.html#upload-your-model-and-dataset-to-giskard-ui
2. https://giskard.readthedocs.io/en/latest/getting-started/test-suite/index.html#create-execute-a-test-suite together with https://giskard.readthedocs.io/en/latest/getting-started/test-suite/index.html#save-a-test-suite

2023-05-02 14:55 UTC, AbSsEnT commented on amazon_review_classification_reference.ipynb
- I'll remove it;
- The link to it is already provided in the header of notebook.

2023-05-04 15:46 UTC, rabah-khalek approved these changes

2023-05-04 15:46 UTC, merged